/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and readiness probe. */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identify the service and the running build. */
        get: operations["getRoot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pokemon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Pokemon, optionally filtered by type. */
        get: operations["listPokemon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pokemon/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One Pokemon by name. */
        get: operations["getPokemon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pokemon/{name}/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every move this Pokemon can learn.
         * @description The full learnable set, which runs to 86 moves for Bulbasaur and 167 for Mewtwo. This is why it is its own endpoint: putting it on the Pokemon object would dominate every list response. The six a Pokemon brings to a battle are on the Pokemon itself.
         */
        get: operations["listPokemonMoves"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every move in the Pokedex. */
        get: operations["listMoves"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moves/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One move by name. */
        get: operations["getMove"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every type present in the Pokedex, with a count. */
        get: operations["listTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe. Checks the database. */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Claim a trainer name and receive a token.
         * @description The token authorises this trainer's moves; the name is public. This is not authentication - it stops one player moving another player's Pokemon, nothing more. Names are first-come, and a name already in use is a 409.
         */
        post: operations["registerTrainer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trainers/waiting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trainers who have an open battle invitation.
         * @description The matchmaking lobby. A trainer appears here after creating a battle and disappears when someone joins it or it expires.
         */
        get: operations["listWaitingTrainers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/battles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a battle and wait for an opponent.
         * @description Names three Pokemon. The battle sits in `waiting` until another trainer joins, which is when turn order is decided.
         */
        post: operations["createBattle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/battles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The full state of one battle.
         * @description Poll this. `version` increases on every change, so a client that has seen a version can skip re-rendering until it moves.
         */
        get: operations["getBattle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/battles/{id}/join": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Join a waiting battle with your own three Pokemon. */
        post: operations["joinBattle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/battles/{id}/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attack with one of your Pokemon.
         * @description Names the attacker, the move and the target. The server decides damage and whether the battle is over. Out-of-turn moves, fainted attackers and illegal targets are 409s rather than silent no-ops, so a client bug is visible instead of looking like lag.
         */
        post: operations["takeTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterTrainer: {
            /** @description Displayed to other trainers in the lobby. */
            name: string;
        };
        Trainer: {
            name: string;
            /** @description Send as X-Trainer-Token. Returned once, at registration. */
            token: string;
        };
        WaitingList: {
            count: number;
            waiting: components["schemas"]["WaitingBattle"][];
        };
        WaitingBattle: {
            battleId: string;
            trainer: string;
            /** @description Who they are bringing, so you can pick a counter. */
            team: string[];
            /** Format: date-time */
            createdAt: string;
        };
        CreateBattle: {
            /** @description Up to three Pokemon names. Anything you leave out is chosen at random, so a client can offer "pick the ones you care about" rather than all-or-nothing - and omitting the field entirely is a full random team, which makes "just start a battle" one click. */
            team?: string[];
        };
        JoinBattle: {
            /** @description Up to three Pokemon names; anything left out is random. */
            team?: string[];
        };
        TakeTurn: {
            /** @description Index into your own team, 0-2. */
            attacker: number;
            /** @description Index into that Pokemon's moves. */
            move: number;
            /** @description Index into the opponent's team, 0-2. */
            target: number;
        };
        Battle: {
            id: string;
            /** @enum {string} */
            status: "waiting" | "active" | "finished";
            /** @description Increases on every change. A client that has rendered version N can skip re-rendering until it sees something higher, which is what makes polling cheap. */
            version: number;
            /** @description Name of the trainer whose turn it is. Absent while waiting and once finished. */
            turn?: string;
            /** @description Set when status is finished. Absent on a draw. */
            winner?: string;
            /** @description Always two once active; one while waiting. */
            sides: components["schemas"]["Side"][];
            /** @description What happened, oldest first. Clients animate from this rather than recomputing events from state diffs. */
            log: components["schemas"]["BattleEvent"][];
        };
        Side: {
            trainer: string;
            team: components["schemas"]["BattlePokemon"][];
        };
        /** @description Stat changes accumulated this battle, -6 to +6. Zero everywhere is the normal state, so a client can skip drawing any of it until something moves. */
        StatStages: {
            attack?: number;
            defense?: number;
            speed?: number;
            accuracy?: number;
        };
        BattlePokemon: {
            name: string;
            types: string[];
            hp: number;
            maxHp: number;
            fainted: boolean;
            sprite: string;
            moves: components["schemas"]["Move"][];
            stages?: components["schemas"]["StatStages"];
            /** @description A confused Pokemon can hit itself instead of attacking, so a client should say so before the player commits a turn. */
            confused?: boolean;
            /** @description Index of a move this Pokemon cannot currently use, or absent. Prefer usableMoves: this is the input the server used, and a client that reads it is re-deriving a conclusion the server has already drawn. */
            disabledMove?: number;
            /** @description Whether this Pokemon can be chosen as the attacker right now. The server decides; a client that computes it from fainted, status and whose turn it is has a second copy of the rules that will drift. */
            canAct?: boolean;
            /** @description Whether this Pokemon is a legal target right now. */
            canBeTargeted?: boolean;
            /** @description One entry per move, in the same order, saying whether it can be selected this turn. Disabled moves and moves with no PP are false. A client greys out the false ones and needs no rules of its own to do it. */
            usableMoves?: boolean[];
        };
        BattleEvent: {
            turnNumber: number;
            /** @description Pre-rendered prose, so three clients narrate a battle identically instead of each inventing wording. */
            text: string;
            attacker?: string;
            target?: string;
            move?: string;
            damage?: number;
            /** @description Type multiplier applied, e.g. 2 for super effective. Clients use it to colour or animate the hit. */
            effectiveness?: number;
            fainted?: boolean;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Identity: {
            service: string;
            version: string;
        };
        Pokemon: {
            /** @description National Pokedex number. */
            id: number;
            name: string;
            /** @description The Pokedex entry, from the most recent game that has one. Flattened to a single line; the games break it for their own text box. */
            description: string;
            /** @description The one-line label the games give it, e.g. "Seed Pokemon". */
            genus: string;
            /** @description Where it is found, e.g. "grassland". Empty for species the games never placed. */
            habitat?: string;
            /** @description One or two types, e.g. ["grass", "poison"]. */
            types: string[];
            /** @description Decimetres, as the upstream Pokedex reports it. */
            height: number;
            /** @description Hectograms, as the upstream Pokedex reports it. */
            weight: number;
            /** @description Absolute URL to the front-facing sprite. */
            sprite: string;
            /** @description Absolute URL to the official artwork, which is several hundred pixels where sprite is 96. */
            artwork?: string;
            /** @description Name of the Pokemon this evolves from; empty if it is a base form. */
            evolvesFrom?: string;
            /** @description True for legendary and mythical Pokemon. */
            legendary?: boolean;
            /** @description The moves this Pokemon brings to a battle. Not everything it could learn - see GET /pokemon/{name}/moves for that. */
            moves: components["schemas"]["Move"][];
        };
        Move: {
            name: string;
            type: string;
            /** @description Base power; 0 for status moves that deal no damage. */
            power: number;
            /** @description How the move looks, in the games' own words. Flattened to a single line. */
            description: string;
            /** @description What the move does mechanically, where description says how it looks. */
            effect: string;
            /** @description Percent chance to hit. Omitted for moves that cannot miss, which is not the same as 100. */
            accuracy?: number;
            /** @description How many times it can be used. */
            pp: number;
            /** @description "physical", "special" or "status". Physical moves read attack and defense, special ones the special stats, and status moves deal no damage. */
            damageClass: string;
        };
        MoveList: {
            count: number;
            moves: components["schemas"]["Move"][];
        };
        PokemonList: {
            count: number;
            pokemon: components["schemas"]["Pokemon"][];
        };
        TypeSummary: {
            name: string;
            count: number;
            /** @description Types this one deals double damage to. Served here so the clients do not each carry a copy of the chart the server computes damage from - three copies is three chances to disagree with the server, and the server is what decides. */
            strongAgainst?: string[];
            /** @description Types this one deals half damage to. */
            weakAgainst?: string[];
            /** @description Types this one cannot damage at all. */
            noEffectAgainst?: string[];
        };
        TypeList: {
            types: components["schemas"]["TypeSummary"][];
        };
        Error: {
            message: string;
        };
    };
    responses: never;
    parameters: {
        /** @description The token returned by POST /trainers. Identifies who is acting, so one player cannot move another player's Pokemon. */
        TrainerToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getRoot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Identity"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listPokemon: {
        parameters: {
            query?: {
                /** @description Filter to Pokemon having this type, e.g. "fire". */
                type?: string;
                /** @description Maximum number to return. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The matching Pokemon, in Pokedex order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PokemonList"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPokemon: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Lowercase name, e.g. "pikachu". */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Pokemon. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pokemon"];
                };
            };
            /** @description No Pokemon by that name. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listPokemonMoves: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Lowercase name, e.g. "pikachu". */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The moves. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveList"];
                };
            };
            /** @description No Pokemon by that name. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listMoves: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The moves. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveList"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Lowercase, hyphenated name, e.g. "vine-whip". */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The move. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Move"];
                };
            };
            /** @description No move by that name. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The types. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeList"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service can reach its database. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description The database is unreachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    registerTrainer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterTrainer"];
            };
        };
        responses: {
            /** @description Registered. Keep the token; it is shown once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trainer"];
                };
            };
            /** @description That name is taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listWaitingTrainers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Open invitations, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaitingList"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createBattle: {
        parameters: {
            query?: never;
            header: {
                /** @description The token returned by POST /trainers. Identifies who is acting, so one player cannot move another player's Pokemon. */
                "X-Trainer-Token": components["parameters"]["TrainerToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBattle"];
            };
        };
        responses: {
            /** @description Battle open, waiting for an opponent. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Battle"];
                };
            };
            /** @description Not three known Pokemon. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown or missing trainer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description This trainer already has a battle waiting for an opponent. One at a time: a trainer can only play the battle they are in, and without the limit one client can fill the lobby and keep it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBattle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Battle"];
                };
            };
            /** @description No such battle, or it expired. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    joinBattle: {
        parameters: {
            query?: never;
            header: {
                /** @description The token returned by POST /trainers. Identifies who is acting, so one player cannot move another player's Pokemon. */
                "X-Trainer-Token": components["parameters"]["TrainerToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinBattle"];
            };
        };
        responses: {
            /** @description Joined. The battle is now active. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Battle"];
                };
            };
            /** @description Not three known Pokemon. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown or missing trainer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such battle. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Already full, or you are already in it. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    takeTurn: {
        parameters: {
            query?: never;
            header: {
                /** @description The token returned by POST /trainers. Identifies who is acting, so one player cannot move another player's Pokemon. */
                "X-Trainer-Token": components["parameters"]["TrainerToken"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TakeTurn"];
            };
        };
        responses: {
            /** @description The turn resolved; state reflects it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Battle"];
                };
            };
            /** @description Unknown or missing trainer token. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such battle. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not your turn, or the move is not legal. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unexpected error. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
