// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: game.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeBattleForTrainer = `-- name: ActiveBattleForTrainer :one
SELECT b.id, b.status, b.version, b.turn, b.turn_number, b.winner,
       b.created_at, b.touched_at, b.state
FROM battles b
JOIN battle_sides s ON s.battle_id = b.id
WHERE s.trainer_token = $1 AND b.status <> 'finished'
ORDER BY b.touched_at DESC
LIMIT 1
`

// Which battle a trainer is in, for a client that reconnects holding
// only its token. The reason battle_sides is a table rather than part
// of the JSONB blob: this is the one question asked across battles,
// and scanning every state document to answer it would not scale past
// a handful.
func (q *Queries) ActiveBattleForTrainer(ctx context.Context, trainerToken string) (Battle, error) {
	row := q.db.QueryRow(ctx, activeBattleForTrainer, trainerToken)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Version,
		&i.Turn,
		&i.TurnNumber,
		&i.Winner,
		&i.CreatedAt,
		&i.TouchedAt,
		&i.State,
	)
	return i, err
}

const addBattleSide = `-- name: AddBattleSide :exec
INSERT INTO battle_sides (battle_id, idx, trainer_token)
VALUES ($1, $2, $3)
ON CONFLICT (battle_id, idx) DO UPDATE SET
    trainer_token = EXCLUDED.trainer_token
`

type AddBattleSideParams struct {
	BattleID     string
	Idx          int32
	TrainerToken string
}

func (q *Queries) AddBattleSide(ctx context.Context, arg AddBattleSideParams) error {
	_, err := q.db.Exec(ctx, addBattleSide, arg.BattleID, arg.Idx, arg.TrainerToken)
	return err
}

const battleSidesFor = `-- name: BattleSidesFor :many
SELECT battle_id, idx, trainer_token
FROM battle_sides WHERE battle_id = $1 ORDER BY idx
`

func (q *Queries) BattleSidesFor(ctx context.Context, battleID string) ([]BattleSide, error) {
	rows, err := q.db.Query(ctx, battleSidesFor, battleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BattleSide
	for rows.Next() {
		var i BattleSide
		if err := rows.Scan(&i.BattleID, &i.Idx, &i.TrainerToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenBattlesFor = `-- name: CountOpenBattlesFor :one
SELECT count(*) FROM battles b
JOIN battle_sides s ON s.battle_id = b.id AND s.idx = 0
WHERE b.status = 'waiting' AND s.trainer_token = $1
`

// How many battles this trainer already has waiting for an opponent.
//
// Guards the lobby: without a cap one trainer can open hundreds in a
// second, and because ListWaitingBattles is ORDER BY created_at DESC
// LIMIT 100 they do not merely crowd the lobby, they own all of it and
// keep owning it. Every real player becomes invisible.
//
// Counts side 0 only, the trainer who opened it. A joiner is side 1 and
// the battle is no longer waiting by then.
func (q *Queries) CountOpenBattlesFor(ctx context.Context, trainerToken string) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenBattlesFor, trainerToken)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBattle = `-- name: CreateBattle :exec
INSERT INTO battles (
    id, status, version, turn, turn_number, winner, state
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateBattleParams struct {
	ID         string
	Status     string
	Version    int32
	Turn       int32
	TurnNumber int32
	Winner     string
	State      []byte
}

func (q *Queries) CreateBattle(ctx context.Context, arg CreateBattleParams) error {
	_, err := q.db.Exec(ctx, createBattle,
		arg.ID,
		arg.Status,
		arg.Version,
		arg.Turn,
		arg.TurnNumber,
		arg.Winner,
		arg.State,
	)
	return err
}

const deleteBattleSidesFrom = `-- name: DeleteBattleSidesFrom :exec
DELETE FROM battle_sides WHERE battle_id = $1 AND idx >= $2
`

type DeleteBattleSidesFromParams struct {
	BattleID string
	Idx      int32
}

// Prune sides at or beyond idx, so a side list that shrinks does not
// leave a stale row behind. Nothing shrinks one today; this keeps the
// table honest if anything ever does.
func (q *Queries) DeleteBattleSidesFrom(ctx context.Context, arg DeleteBattleSidesFromParams) error {
	_, err := q.db.Exec(ctx, deleteBattleSidesFrom, arg.BattleID, arg.Idx)
	return err
}

const getBattle = `-- name: GetBattle :one
SELECT id, status, version, turn, turn_number, winner,
       created_at, touched_at, state
FROM battles WHERE id = $1
`

func (q *Queries) GetBattle(ctx context.Context, id string) (Battle, error) {
	row := q.db.QueryRow(ctx, getBattle, id)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Version,
		&i.Turn,
		&i.TurnNumber,
		&i.Winner,
		&i.CreatedAt,
		&i.TouchedAt,
		&i.State,
	)
	return i, err
}

const getBattleForUpdate = `-- name: GetBattleForUpdate :one
SELECT id, status, version, turn, turn_number, winner,
       created_at, touched_at, state
FROM battles WHERE id = $1
`

// The read half of update(). Inside a SERIALIZABLE transaction this
// is what Postgres tracks to detect a conflicting write: two pods
// reading the same row and both writing it means one gets 40001 and
// retries, rather than silently clobbering the other.
func (q *Queries) GetBattleForUpdate(ctx context.Context, id string) (Battle, error) {
	row := q.db.QueryRow(ctx, getBattleForUpdate, id)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Version,
		&i.Turn,
		&i.TurnNumber,
		&i.Winner,
		&i.CreatedAt,
		&i.TouchedAt,
		&i.State,
	)
	return i, err
}

const listWaitingBattles = `-- name: ListWaitingBattles :many
SELECT id, status, version, turn, turn_number, winner,
       created_at, touched_at, state
FROM battles
WHERE status = 'waiting'
ORDER BY created_at DESC
LIMIT 100
`

// The lobby: open invitations, newest first.
//
// LIMIT, because every row here has its state JSONB deserialised in
// Go. Unbounded, a busy lobby decodes the whole table on every
// request, and the decoding is the cliff rather than the scan.
//
// The LIMIT also changes the plan: without one the planner picks a
// bitmap scan and sorts afterwards, so the DESC in the index buys
// nothing. Measured at 200k battles - 17ms with a sort, 0.1ms with
// this plus the partial index from migration 003.
func (q *Queries) ListWaitingBattles(ctx context.Context) ([]Battle, error) {
	rows, err := q.db.Query(ctx, listWaitingBattles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Battle
	for rows.Next() {
		var i Battle
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Version,
			&i.Turn,
			&i.TurnNumber,
			&i.Winner,
			&i.CreatedAt,
			&i.TouchedAt,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerTrainer = `-- name: RegisterTrainer :one

INSERT INTO trainers (token, name) VALUES ($1, $2)
RETURNING token, name, created_at, last_seen
`

type RegisterTrainerParams struct {
	Token string
	Name  string
}

// Game state: trainers and battles.
//
// Unlike the reference queries, these run on the request path. Every
// one of them is what makes two replicas safe - the guarantees are in
// the SQL rather than in a mutex the other pod cannot see.
// Claims a name and returns the token.
//
// The race this settles: two clients registering "ash" at the same
// moment. lower(name) is UNIQUE, so exactly one INSERT succeeds and
// the other gets a constraint violation the caller turns into
// errNameTaken. A read-then-write check would let both through.
func (q *Queries) RegisterTrainer(ctx context.Context, arg RegisterTrainerParams) (Trainer, error) {
	row := q.db.QueryRow(ctx, registerTrainer, arg.Token, arg.Name)
	var i Trainer
	err := row.Scan(
		&i.Token,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const sweepBattles = `-- name: SweepBattles :exec
DELETE FROM battles WHERE id IN (
    SELECT b.id FROM battles b
    WHERE (b.status <> 'waiting' AND b.touched_at < $1)
       OR (b.status =  'waiting' AND b.touched_at < $2)
    ORDER BY b.touched_at
    LIMIT $3
)
`

type SweepBattlesParams struct {
	ActiveBefore  pgtype.Timestamptz
	WaitingBefore pgtype.Timestamptz
	BatchSize     int32
}

// Drops battles nobody has touched inside the TTL.
//
// Called on write rather than from a timer: there is no background
// goroutine to supervise, a store that is never written does not
// grow, and with several replicas a timer in each would mean several
// sweeps racing. battle_sides goes with it by ON DELETE CASCADE.
//
// Two cutoffs, because touched_at means different things for the two
// statuses. An active battle is touched by every turn, so a stale
// touched_at genuinely means abandoned. A WAITING battle is never
// touched at all - a join is its first update - so its touched_at is
// just its creation time, and one cutoff deleted players who were
// sitting in the lobby doing exactly what they should.
// Bounded, because an unbounded DELETE here is a user's request.
//
// With a backlog - any outage, restart gap or traffic spike leaves
// one - the predicate stops being selective, the planner abandons
// battles_touched_idx for a sequential scan, and the FK cascade fires
// once per row. Measured at 193k expired battles: 992ms and 193,000
// trigger calls, inside POST /battles and the lobby GET. With several
// replicas each serving a lobby load, those all issue the same DELETE
// and contend on the same rows.
//
// A limit caps the worst case at something a request can absorb -
// 37ms and 1,000 trigger calls for the same backlog - and still
// drains it across successive writes, oldest first. Steady state is
// unaffected: 5.8ms unbounded vs 3.1ms batched, with nothing to
// delete.
func (q *Queries) SweepBattles(ctx context.Context, arg SweepBattlesParams) error {
	_, err := q.db.Exec(ctx, sweepBattles, arg.ActiveBefore, arg.WaitingBefore, arg.BatchSize)
	return err
}

const sweepTrainers = `-- name: SweepTrainers :exec
DELETE FROM trainers t
WHERE t.last_seen < $1
  AND NOT EXISTS (SELECT 1 FROM battle_sides s WHERE s.trainer_token = t.token)
`

// Drops trainers nobody has been in a long time, so a name someone
// registered once and abandoned can be claimed again. Names are unique
// and were never released, so without this every name is spent the
// moment it is typed - including by whoever loses their token.
//
// NOT IN a battle, whatever last_seen says. A trainer waiting in the
// lobby for an opponent may sit for hours without making a request,
// and deleting them would cascade their side away and strand the other
// player mid-game. Battles are swept on their own TTL first, so a
// trainer only becomes sweepable once their battles have gone.
//
// Called on write, like SweepBattles: no background goroutine to
// supervise, and no timer in each replica racing the others.
// NOT EXISTS rather than NOT IN. Both delete exactly the same rows -
// battle_sides.trainer_token is NOT NULL, so the three-valued logic
// that usually distinguishes them cannot apply - but NOT IN makes the
// planner build the whole battle_sides set before it can answer, while
// NOT EXISTS is an anti-join it can satisfy per row from the index.
// At 200k trainers, steady state with nothing to sweep: 66ms -> 22ms,
// on every lobby load.
func (q *Queries) SweepTrainers(ctx context.Context, lastSeen pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, sweepTrainers, lastSeen)
	return err
}

const touchTrainer = `-- name: TouchTrainer :exec
UPDATE trainers SET last_seen = now() WHERE token = $1
`

// Records that a token was used, which is what SweepTrainers reads.
// Separate from TrainerByToken so a read stays a read.
func (q *Queries) TouchTrainer(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, touchTrainer, token)
	return err
}

const trainerByToken = `-- name: TrainerByToken :one
SELECT token, name, created_at, last_seen FROM trainers WHERE token = $1
`

func (q *Queries) TrainerByToken(ctx context.Context, token string) (Trainer, error) {
	row := q.db.QueryRow(ctx, trainerByToken, token)
	var i Trainer
	err := row.Scan(
		&i.Token,
		&i.Name,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const updateBattle = `-- name: UpdateBattle :exec
UPDATE battles SET
    status = $2,
    version = version + 1,
    turn = $3,
    turn_number = $4,
    winner = $5,
    state = $6,
    touched_at = now()
WHERE id = $1
`

type UpdateBattleParams struct {
	ID         string
	Status     string
	Turn       int32
	TurnNumber int32
	Winner     string
	State      []byte
}

// version is bumped here rather than by the caller, so no path can
// write a battle and forget to move it. Clients poll and compare
// version, so one that does not change reads as "nothing happened".
func (q *Queries) UpdateBattle(ctx context.Context, arg UpdateBattleParams) error {
	_, err := q.db.Exec(ctx, updateBattle,
		arg.ID,
		arg.Status,
		arg.Turn,
		arg.TurnNumber,
		arg.Winner,
		arg.State,
	)
	return err
}
