// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Battle struct {
	ID         string
	Status     string
	Version    int32
	Turn       int32
	TurnNumber int32
	Winner     string
	CreatedAt  pgtype.Timestamptz
	TouchedAt  pgtype.Timestamptz
	State      []byte
}

type BattleSide struct {
	BattleID     string
	Idx          int32
	TrainerToken string
}

type Move struct {
	Name        string
	Type        string
	Power       int32
	Description string
	Effect      string
	Accuracy    *int32
	Pp          int32
	DamageClass string
}

type Pokemon struct {
	ID                 int32
	Name               string
	Description        string
	Genus              string
	Habitat            string
	Types              []string
	Height             int32
	Weight             int32
	Sprite             string
	Artwork            string
	EvolvesFrom        string
	Legendary          bool
	BaseHp             int32
	BaseAttack         int32
	BaseDefense        int32
	BaseSpecialAttack  int32
	BaseSpecialDefense int32
	BaseSpeed          int32
}

type PokemonMove struct {
	PokemonID int32
	MoveName  string
	Kind      string
	Slot      int32
}

type SchemaMigration struct {
	Version   int32
	AppliedAt pgtype.Timestamptz
}

type Trainer struct {
	Token     string
	Name      string
	CreatedAt pgtype.Timestamptz
	LastSeen  pgtype.Timestamptz
}
