// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Which battle a trainer is in, for a client that reconnects holding
	// only its token. The reason battle_sides is a table rather than part
	// of the JSONB blob: this is the one question asked across battles,
	// and scanning every state document to answer it would not scale past
	// a handful.
	ActiveBattleForTrainer(ctx context.Context, trainerToken string) (Battle, error)
	AddBattleSide(ctx context.Context, arg AddBattleSideParams) error
	BattleSidesFor(ctx context.Context, battleID string) ([]BattleSide, error)
	CountPokemon(ctx context.Context) (int64, error)
	CreateBattle(ctx context.Context, arg CreateBattleParams) error
	// Prune sides at or beyond idx, so a side list that shrinks does not
	// leave a stale row behind. Nothing shrinks one today; this keeps the
	// table honest if anything ever does.
	DeleteBattleSidesFrom(ctx context.Context, arg DeleteBattleSidesFromParams) error
	// Clears a Pokemon's links before re-seeding them, so a move dropped
	// upstream does not linger. Scoped to one Pokemon rather than
	// truncating the table, which would break the foreign key for every
	// other row mid-seed.
	DeletePokemonMovesFor(ctx context.Context, pokemonID int32) error
	GetBattle(ctx context.Context, id string) (Battle, error)
	// The read half of update(). Inside a SERIALIZABLE transaction this
	// is what Postgres tracks to detect a conflicting write: two pods
	// reading the same row and both writing it means one gets 40001 and
	// retries, rather than silently clobbering the other.
	GetBattleForUpdate(ctx context.Context, id string) (Battle, error)
	ListMoves(ctx context.Context) ([]Move, error)
	// Reference data: the Pokedex itself.
	//
	// Read at startup and held in memory. It is 100 Pokemon and 562 moves
	// that never change between deploys, so querying per request would buy
	// nothing and put the database on the path of every /pokemon call.
	// The database is the source of truth; this is a cache of it that
	// lives as long as the process.
	ListPokemon(ctx context.Context) ([]Pokemon, error)
	// Every Pokemon-to-move link, both kinds, in the order the upstream
	// Pokedex gave them. Loaded whole and grouped in Go rather than joined
	// per Pokemon: it is one query instead of a hundred.
	ListPokemonMoves(ctx context.Context) ([]PokemonMove, error)
	// The lobby: open invitations, newest first.
	//
	// LIMIT, because every row here has its state JSONB deserialised in
	// Go. Unbounded, a busy lobby decodes the whole table on every
	// request, and the decoding is the cliff rather than the scan.
	//
	// The LIMIT also changes the plan: without one the planner picks a
	// bitmap scan and sorts afterwards, so the DESC in the index buys
	// nothing. Measured at 200k battles - 17ms with a sort, 0.1ms with
	// this plus the partial index from migration 003.
	ListWaitingBattles(ctx context.Context) ([]Battle, error)
	// Game state: trainers and battles.
	//
	// Unlike the reference queries, these run on the request path. Every
	// one of them is what makes two replicas safe - the guarantees are in
	// the SQL rather than in a mutex the other pod cannot see.
	// Claims a name and returns the token.
	//
	// The race this settles: two clients registering "ash" at the same
	// moment. lower(name) is UNIQUE, so exactly one INSERT succeeds and
	// the other gets a constraint violation the caller turns into
	// errNameTaken. A read-then-write check would let both through.
	RegisterTrainer(ctx context.Context, arg RegisterTrainerParams) (Trainer, error)
	// Drops battles nobody has touched inside the TTL.
	//
	// Called on write rather than from a timer: there is no background
	// goroutine to supervise, a store that is never written does not
	// grow, and with several replicas a timer in each would mean several
	// sweeps racing. battle_sides goes with it by ON DELETE CASCADE.
	SweepBattles(ctx context.Context, touchedAt pgtype.Timestamptz) error
	// Drops trainers nobody has been in a long time, so a name someone
	// registered once and abandoned can be claimed again. Names are unique
	// and were never released, so without this every name is spent the
	// moment it is typed - including by whoever loses their token.
	//
	// NOT IN a battle, whatever last_seen says. A trainer waiting in the
	// lobby for an opponent may sit for hours without making a request,
	// and deleting them would cascade their side away and strand the other
	// player mid-game. Battles are swept on their own TTL first, so a
	// trainer only becomes sweepable once their battles have gone.
	//
	// Called on write, like SweepBattles: no background goroutine to
	// supervise, and no timer in each replica racing the others.
	// NOT EXISTS rather than NOT IN. Both delete exactly the same rows -
	// battle_sides.trainer_token is NOT NULL, so the three-valued logic
	// that usually distinguishes them cannot apply - but NOT IN makes the
	// planner build the whole battle_sides set before it can answer, while
	// NOT EXISTS is an anti-join it can satisfy per row from the index.
	// At 200k trainers, steady state with nothing to sweep: 66ms -> 22ms,
	// on every lobby load.
	SweepTrainers(ctx context.Context, lastSeen pgtype.Timestamptz) error
	// Records that a token was used, which is what SweepTrainers reads.
	// Separate from TrainerByToken so a read stays a read.
	TouchTrainer(ctx context.Context, token string) error
	TrainerByToken(ctx context.Context, token string) (Trainer, error)
	// version is bumped here rather than by the caller, so no path can
	// write a battle and forget to move it. Clients poll and compare
	// version, so one that does not change reads as "nothing happened".
	UpdateBattle(ctx context.Context, arg UpdateBattleParams) error
	UpsertMove(ctx context.Context, arg UpsertMoveParams) error
	// Seeding. Run once from pokedex.json when the tables are empty.
	//
	// ON CONFLICT DO UPDATE rather than DO NOTHING: re-seeding after the
	// data file changes should update what is there, and a seed that
	// silently skips existing rows would leave the database on an old
	// version of the Pokedex with no sign of it.
	UpsertPokemon(ctx context.Context, arg UpsertPokemonParams) error
	// Every link in one statement. unnest turns four parallel arrays into
	// rows, so seeding is one round trip instead of ~9,000.
	UpsertPokemonMoves(ctx context.Context, arg UpsertPokemonMovesParams) error
}

var _ Querier = (*Queries)(nil)
