// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reference.sql

package dbgen

import (
	"context"
)

const countPokemon = `-- name: CountPokemon :one
SELECT count(*) FROM pokemon
`

func (q *Queries) CountPokemon(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPokemon)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePokemonMovesFor = `-- name: DeletePokemonMovesFor :exec
DELETE FROM pokemon_moves WHERE pokemon_id = $1
`

// Clears a Pokemon's links before re-seeding them, so a move dropped
// upstream does not linger. Scoped to one Pokemon rather than
// truncating the table, which would break the foreign key for every
// other row mid-seed.
func (q *Queries) DeletePokemonMovesFor(ctx context.Context, pokemonID int32) error {
	_, err := q.db.Exec(ctx, deletePokemonMovesFor, pokemonID)
	return err
}

const listMoves = `-- name: ListMoves :many
SELECT name, type, power, description, effect, accuracy, pp, damage_class FROM moves ORDER BY name
`

func (q *Queries) ListMoves(ctx context.Context) ([]Move, error) {
	rows, err := q.db.Query(ctx, listMoves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Move
	for rows.Next() {
		var i Move
		if err := rows.Scan(
			&i.Name,
			&i.Type,
			&i.Power,
			&i.Description,
			&i.Effect,
			&i.Accuracy,
			&i.Pp,
			&i.DamageClass,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPokemon = `-- name: ListPokemon :many

SELECT id, name, description, genus, habitat, types, height, weight, sprite, artwork, evolves_from, legendary, base_hp, base_attack, base_defense, base_special_attack, base_special_defense, base_speed FROM pokemon ORDER BY id
`

// Reference data: the Pokedex itself.
//
// Read at startup and held in memory. It is 100 Pokemon and 562 moves
// that never change between deploys, so querying per request would buy
// nothing and put the database on the path of every /pokemon call.
// The database is the source of truth; this is a cache of it that
// lives as long as the process.
func (q *Queries) ListPokemon(ctx context.Context) ([]Pokemon, error) {
	rows, err := q.db.Query(ctx, listPokemon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pokemon
	for rows.Next() {
		var i Pokemon
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Genus,
			&i.Habitat,
			&i.Types,
			&i.Height,
			&i.Weight,
			&i.Sprite,
			&i.Artwork,
			&i.EvolvesFrom,
			&i.Legendary,
			&i.BaseHp,
			&i.BaseAttack,
			&i.BaseDefense,
			&i.BaseSpecialAttack,
			&i.BaseSpecialDefense,
			&i.BaseSpeed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPokemonMoves = `-- name: ListPokemonMoves :many
SELECT pokemon_id, move_name, kind, slot
FROM pokemon_moves
ORDER BY pokemon_id, kind, slot
`

// Every Pokemon-to-move link, both kinds, in the order the upstream
// Pokedex gave them. Loaded whole and grouped in Go rather than joined
// per Pokemon: it is one query instead of a hundred.
func (q *Queries) ListPokemonMoves(ctx context.Context) ([]PokemonMove, error) {
	rows, err := q.db.Query(ctx, listPokemonMoves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PokemonMove
	for rows.Next() {
		var i PokemonMove
		if err := rows.Scan(
			&i.PokemonID,
			&i.MoveName,
			&i.Kind,
			&i.Slot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMove = `-- name: UpsertMove :exec
INSERT INTO moves (
    name, type, power, description, effect, accuracy, pp, damage_class
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (name) DO UPDATE SET
    type = EXCLUDED.type,
    power = EXCLUDED.power,
    description = EXCLUDED.description,
    effect = EXCLUDED.effect,
    accuracy = EXCLUDED.accuracy,
    pp = EXCLUDED.pp,
    damage_class = EXCLUDED.damage_class
`

type UpsertMoveParams struct {
	Name        string
	Type        string
	Power       int32
	Description string
	Effect      string
	Accuracy    *int32
	Pp          int32
	DamageClass string
}

func (q *Queries) UpsertMove(ctx context.Context, arg UpsertMoveParams) error {
	_, err := q.db.Exec(ctx, upsertMove,
		arg.Name,
		arg.Type,
		arg.Power,
		arg.Description,
		arg.Effect,
		arg.Accuracy,
		arg.Pp,
		arg.DamageClass,
	)
	return err
}

const upsertPokemon = `-- name: UpsertPokemon :exec

INSERT INTO pokemon (
    id, name, description, genus, habitat, types, height, weight,
    sprite, artwork, evolves_from, legendary,
    base_hp, base_attack, base_defense,
    base_special_attack, base_special_defense, base_speed
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    genus = EXCLUDED.genus,
    habitat = EXCLUDED.habitat,
    types = EXCLUDED.types,
    height = EXCLUDED.height,
    weight = EXCLUDED.weight,
    sprite = EXCLUDED.sprite,
    artwork = EXCLUDED.artwork,
    evolves_from = EXCLUDED.evolves_from,
    legendary = EXCLUDED.legendary,
    base_hp = EXCLUDED.base_hp,
    base_attack = EXCLUDED.base_attack,
    base_defense = EXCLUDED.base_defense,
    base_special_attack = EXCLUDED.base_special_attack,
    base_special_defense = EXCLUDED.base_special_defense,
    base_speed = EXCLUDED.base_speed
`

type UpsertPokemonParams struct {
	ID                 int32
	Name               string
	Description        string
	Genus              string
	Habitat            string
	Types              []string
	Height             int32
	Weight             int32
	Sprite             string
	Artwork            string
	EvolvesFrom        string
	Legendary          bool
	BaseHp             int32
	BaseAttack         int32
	BaseDefense        int32
	BaseSpecialAttack  int32
	BaseSpecialDefense int32
	BaseSpeed          int32
}

// Seeding. Run once from pokedex.json when the tables are empty.
//
// ON CONFLICT DO UPDATE rather than DO NOTHING: re-seeding after the
// data file changes should update what is there, and a seed that
// silently skips existing rows would leave the database on an old
// version of the Pokedex with no sign of it.
func (q *Queries) UpsertPokemon(ctx context.Context, arg UpsertPokemonParams) error {
	_, err := q.db.Exec(ctx, upsertPokemon,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Genus,
		arg.Habitat,
		arg.Types,
		arg.Height,
		arg.Weight,
		arg.Sprite,
		arg.Artwork,
		arg.EvolvesFrom,
		arg.Legendary,
		arg.BaseHp,
		arg.BaseAttack,
		arg.BaseDefense,
		arg.BaseSpecialAttack,
		arg.BaseSpecialDefense,
		arg.BaseSpeed,
	)
	return err
}

const upsertPokemonMove = `-- name: UpsertPokemonMove :exec
INSERT INTO pokemon_moves (pokemon_id, move_name, kind, slot)
VALUES ($1, $2, $3, $4)
ON CONFLICT (pokemon_id, move_name, kind) DO UPDATE SET
    slot = EXCLUDED.slot
`

type UpsertPokemonMoveParams struct {
	PokemonID int32
	MoveName  string
	Kind      string
	Slot      int32
}

func (q *Queries) UpsertPokemonMove(ctx context.Context, arg UpsertPokemonMoveParams) error {
	_, err := q.db.Exec(ctx, upsertPokemonMove,
		arg.PokemonID,
		arg.MoveName,
		arg.Kind,
		arg.Slot,
	)
	return err
}
