apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokedex
  namespace: pokedex
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: external
  tls:
    - hosts: [pokemon.home.chrisscotmartin.com]
      secretName: pokedex-tls
  rules:
    - host: pokemon.home.chrisscotmartin.com
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: pokedex
                port:
                  number: 80
