// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateBattleOperation        OperationName = "CreateBattle"
	GetBattleOperation           OperationName = "GetBattle"
	GetHealthzOperation          OperationName = "GetHealthz"
	GetMoveOperation             OperationName = "GetMove"
	GetPokemonOperation          OperationName = "GetPokemon"
	GetReadyzOperation           OperationName = "GetReadyz"
	GetRootOperation             OperationName = "GetRoot"
	JoinBattleOperation          OperationName = "JoinBattle"
	ListMovesOperation           OperationName = "ListMoves"
	ListPokemonOperation         OperationName = "ListPokemon"
	ListPokemonMovesOperation    OperationName = "ListPokemonMoves"
	ListTypesOperation           OperationName = "ListTypes"
	ListWaitingTrainersOperation OperationName = "ListWaitingTrainers"
	RegisterTrainerOperation     OperationName = "RegisterTrainer"
	TakeTurnOperation            OperationName = "TakeTurn"
)
