// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateBattle implements createBattle operation.
//
// Names three Pokemon. The battle sits in `waiting` until another trainer joins, which is when turn
// order is decided.
//
// POST /battles
func (UnimplementedHandler) CreateBattle(ctx context.Context, req *CreateBattle, params CreateBattleParams) (r CreateBattleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBattle implements getBattle operation.
//
// Poll this. `version` increases on every change, so a client that has seen a version can skip
// re-rendering until it moves.
//
// GET /battles/{id}
func (UnimplementedHandler) GetBattle(ctx context.Context, params GetBattleParams) (r GetBattleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealthz implements getHealthz operation.
//
// Liveness and readiness probe.
//
// GET /healthz
func (UnimplementedHandler) GetHealthz(ctx context.Context) (r *Health, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMove implements getMove operation.
//
// One move by name.
//
// GET /moves/{name}
func (UnimplementedHandler) GetMove(ctx context.Context, params GetMoveParams) (r GetMoveRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPokemon implements getPokemon operation.
//
// One Pokemon by name.
//
// GET /pokemon/{name}
func (UnimplementedHandler) GetPokemon(ctx context.Context, params GetPokemonParams) (r GetPokemonRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRoot implements getRoot operation.
//
// Identify the service and the running build.
//
// GET /
func (UnimplementedHandler) GetRoot(ctx context.Context) (r *Identity, _ error) {
	return r, ht.ErrNotImplemented
}

// JoinBattle implements joinBattle operation.
//
// Join a waiting battle with your own three Pokemon.
//
// POST /battles/{id}/join
func (UnimplementedHandler) JoinBattle(ctx context.Context, req *JoinBattle, params JoinBattleParams) (r JoinBattleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMoves implements listMoves operation.
//
// Every move in the Pokedex.
//
// GET /moves
func (UnimplementedHandler) ListMoves(ctx context.Context) (r *MoveList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPokemon implements listPokemon operation.
//
// List Pokemon, optionally filtered by type.
//
// GET /pokemon
func (UnimplementedHandler) ListPokemon(ctx context.Context, params ListPokemonParams) (r *PokemonList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPokemonMoves implements listPokemonMoves operation.
//
// The full learnable set, which runs to 86 moves for Bulbasaur and 167 for Mewtwo. This is why it is
// its own endpoint: putting it on the Pokemon object would dominate every list response. The six a
// Pokemon brings to a battle are on the Pokemon itself.
//
// GET /pokemon/{name}/moves
func (UnimplementedHandler) ListPokemonMoves(ctx context.Context, params ListPokemonMovesParams) (r ListPokemonMovesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTypes implements listTypes operation.
//
// Every type present in the Pokedex, with a count.
//
// GET /types
func (UnimplementedHandler) ListTypes(ctx context.Context) (r *TypeList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWaitingTrainers implements listWaitingTrainers operation.
//
// The matchmaking lobby. A trainer appears here after creating a battle and disappears when someone
// joins it or it expires.
//
// GET /trainers/waiting
func (UnimplementedHandler) ListWaitingTrainers(ctx context.Context) (r *WaitingList, _ error) {
	return r, ht.ErrNotImplemented
}

// RegisterTrainer implements registerTrainer operation.
//
// The token authorises this trainer's moves; the name is public. This is not authentication - it stops
// one player moving another player's Pokemon, nothing more. Names are first-come, and a name already
// in use is a 409.
//
// POST /trainers
func (UnimplementedHandler) RegisterTrainer(ctx context.Context, req *RegisterTrainer) (r RegisterTrainerRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TakeTurn implements takeTurn operation.
//
// Names the attacker, the move and the target. The server decides damage and whether the battle is
// over. Out-of-turn moves, fainted attackers and illegal targets are 409s rather than silent no-ops,
// so a client bug is visible instead of looking like lag.
//
// POST /battles/{id}/turn
func (UnimplementedHandler) TakeTurn(ctx context.Context, req *TakeTurn, params TakeTurnParams) (r TakeTurnRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
