// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetHealthz implements getHealthz operation.
//
// Liveness and readiness probe.
//
// GET /healthz
func (UnimplementedHandler) GetHealthz(ctx context.Context) (r *Health, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPokemon implements getPokemon operation.
//
// One Pokemon by name.
//
// GET /pokemon/{name}
func (UnimplementedHandler) GetPokemon(ctx context.Context, params GetPokemonParams) (r GetPokemonRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRoot implements getRoot operation.
//
// Identify the service and the running build.
//
// GET /
func (UnimplementedHandler) GetRoot(ctx context.Context) (r *Identity, _ error) {
	return r, ht.ErrNotImplemented
}

// ListPokemon implements listPokemon operation.
//
// List Pokemon, optionally filtered by type.
//
// GET /pokemon
func (UnimplementedHandler) ListPokemon(ctx context.Context, params ListPokemonParams) (r *PokemonList, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTypes implements listTypes operation.
//
// Every type present in the Pokedex, with a count.
//
// GET /types
func (UnimplementedHandler) ListTypes(ctx context.Context) (r *TypeList, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
