// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
	"io"
	"net/url"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// GetHealthz invokes getHealthz operation.
	//
	// Liveness and readiness probe.
	//
	// GET /healthz
	GetHealthz(ctx context.Context) (*Health, error)
	// GetPokemon invokes getPokemon operation.
	//
	// One Pokemon by name.
	//
	// GET /pokemon/{name}
	GetPokemon(ctx context.Context, params GetPokemonParams) (GetPokemonRes, error)
	// GetRoot invokes getRoot operation.
	//
	// Identify the service and the running build.
	//
	// GET /
	GetRoot(ctx context.Context) (*Identity, error)
	// ListPokemon invokes listPokemon operation.
	//
	// List Pokemon, optionally filtered by type.
	//
	// GET /pokemon
	ListPokemon(ctx context.Context, params ListPokemonParams) (*PokemonList, error)
	// ListTypes invokes listTypes operation.
	//
	// Every type present in the Pokedex, with a count.
	//
	// GET /types
	ListTypes(ctx context.Context) (*TypeList, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// GetHealthz invokes getHealthz operation.
//
// Liveness and readiness probe.
//
// GET /healthz
func (c *Client) GetHealthz(ctx context.Context) (*Health, error) {
	res, err := c.sendGetHealthz(ctx)
	return res, err
}

func (c *Client) sendGetHealthz(ctx context.Context) (res *Health, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/healthz"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeGetHealthzResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetPokemon invokes getPokemon operation.
//
// One Pokemon by name.
//
// GET /pokemon/{name}
func (c *Client) GetPokemon(ctx context.Context, params GetPokemonParams) (GetPokemonRes, error) {
	res, err := c.sendGetPokemon(ctx, params)
	return res, err
}

func (c *Client) sendGetPokemon(ctx context.Context, params GetPokemonParams) (res GetPokemonRes, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [2]string
	pathParts[0] = "/pokemon/"
	{
		// Encode "name" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "name",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Name))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeGetPokemonResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// GetRoot invokes getRoot operation.
//
// Identify the service and the running build.
//
// GET /
func (c *Client) GetRoot(ctx context.Context) (*Identity, error) {
	res, err := c.sendGetRoot(ctx)
	return res, err
}

func (c *Client) sendGetRoot(ctx context.Context) (res *Identity, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeGetRootResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListPokemon invokes listPokemon operation.
//
// List Pokemon, optionally filtered by type.
//
// GET /pokemon
func (c *Client) ListPokemon(ctx context.Context, params ListPokemonParams) (*PokemonList, error) {
	res, err := c.sendListPokemon(ctx, params)
	return res, err
}

func (c *Client) sendListPokemon(ctx context.Context, params ListPokemonParams) (res *PokemonList, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/pokemon"
	uri.AddPathParts(u, pathParts[:]...)

	q := uri.NewQueryEncoder()
	{
		// Encode "type" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "type",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Type.Get(); ok {
				return e.EncodeValue(conv.StringToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	{
		// Encode "limit" parameter.
		cfg := uri.QueryParameterEncodingConfig{
			Name:    "limit",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
			if val, ok := params.Limit.Get(); ok {
				return e.EncodeValue(conv.IntToString(val))
			}
			return nil
		}); err != nil {
			return res, errors.Wrap(err, "encode query")
		}
	}
	u.RawQuery = q.Values().Encode()

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeListPokemonResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ListTypes invokes listTypes operation.
//
// Every type present in the Pokedex, with a count.
//
// GET /types
func (c *Client) ListTypes(ctx context.Context) (*TypeList, error) {
	res, err := c.sendListTypes(ctx)
	return res, err
}

func (c *Client) sendListTypes(ctx context.Context) (res *TypeList, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/types"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "GET", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeListTypesResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
