// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetHealthzOperation  OperationName = "GetHealthz"
	GetPokemonOperation  OperationName = "GetPokemon"
	GetRootOperation     OperationName = "GetRoot"
	ListPokemonOperation OperationName = "ListPokemon"
	ListTypesOperation   OperationName = "ListTypes"
)
