// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"

	"github.com/go-faster/errors"
)

func (s *ErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Error
type Error struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) getPokemonRes() {}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

// Ref: #/components/schemas/Health
type Health struct {
	Status HealthStatus `json:"status"`
}

// GetStatus returns the value of Status.
func (s *Health) GetStatus() HealthStatus {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *Health) SetStatus(val HealthStatus) {
	s.Status = val
}

type HealthStatus string

const (
	HealthStatusOk HealthStatus = "ok"
)

// AllValues returns all HealthStatus values.
func (HealthStatus) AllValues() []HealthStatus {
	return []HealthStatus{
		HealthStatusOk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s HealthStatus) MarshalText() ([]byte, error) {
	switch s {
	case HealthStatusOk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *HealthStatus) UnmarshalText(data []byte) error {
	switch HealthStatus(data) {
	case HealthStatusOk:
		*s = HealthStatusOk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Identity
type Identity struct {
	Service string `json:"service"`
	Version string `json:"version"`
}

// GetService returns the value of Service.
func (s *Identity) GetService() string {
	return s.Service
}

// GetVersion returns the value of Version.
func (s *Identity) GetVersion() string {
	return s.Version
}

// SetService sets the value of Service.
func (s *Identity) SetService(val string) {
	s.Service = val
}

// SetVersion sets the value of Version.
func (s *Identity) SetVersion(val string) {
	s.Version = val
}

// Ref: #/components/schemas/Move
type Move struct {
	Name string `json:"name"`
	Type string `json:"type"`
	// Base power; 0 for status moves that deal no damage.
	Power int `json:"power"`
}

// GetName returns the value of Name.
func (s *Move) GetName() string {
	return s.Name
}

// GetType returns the value of Type.
func (s *Move) GetType() string {
	return s.Type
}

// GetPower returns the value of Power.
func (s *Move) GetPower() int {
	return s.Power
}

// SetName sets the value of Name.
func (s *Move) SetName(val string) {
	s.Name = val
}

// SetType sets the value of Type.
func (s *Move) SetType(val string) {
	s.Type = val
}

// SetPower sets the value of Power.
func (s *Move) SetPower(val int) {
	s.Power = val
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Pokemon
type Pokemon struct {
	// National Pokedex number.
	ID   int    `json:"id"`
	Name string `json:"name"`
	// One or two types, e.g. ["grass", "poison"].
	Types []string `json:"types"`
	// Decimetres, as the upstream Pokedex reports it.
	Height int `json:"height"`
	// Hectograms, as the upstream Pokedex reports it.
	Weight int `json:"weight"`
	// Absolute URL to the front-facing sprite.
	Sprite string `json:"sprite"`
	Moves  []Move `json:"moves"`
}

// GetID returns the value of ID.
func (s *Pokemon) GetID() int {
	return s.ID
}

// GetName returns the value of Name.
func (s *Pokemon) GetName() string {
	return s.Name
}

// GetTypes returns the value of Types.
func (s *Pokemon) GetTypes() []string {
	return s.Types
}

// GetHeight returns the value of Height.
func (s *Pokemon) GetHeight() int {
	return s.Height
}

// GetWeight returns the value of Weight.
func (s *Pokemon) GetWeight() int {
	return s.Weight
}

// GetSprite returns the value of Sprite.
func (s *Pokemon) GetSprite() string {
	return s.Sprite
}

// GetMoves returns the value of Moves.
func (s *Pokemon) GetMoves() []Move {
	return s.Moves
}

// SetID sets the value of ID.
func (s *Pokemon) SetID(val int) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Pokemon) SetName(val string) {
	s.Name = val
}

// SetTypes sets the value of Types.
func (s *Pokemon) SetTypes(val []string) {
	s.Types = val
}

// SetHeight sets the value of Height.
func (s *Pokemon) SetHeight(val int) {
	s.Height = val
}

// SetWeight sets the value of Weight.
func (s *Pokemon) SetWeight(val int) {
	s.Weight = val
}

// SetSprite sets the value of Sprite.
func (s *Pokemon) SetSprite(val string) {
	s.Sprite = val
}

// SetMoves sets the value of Moves.
func (s *Pokemon) SetMoves(val []Move) {
	s.Moves = val
}

func (*Pokemon) getPokemonRes() {}

// Ref: #/components/schemas/PokemonList
type PokemonList struct {
	Count   int       `json:"count"`
	Pokemon []Pokemon `json:"pokemon"`
}

// GetCount returns the value of Count.
func (s *PokemonList) GetCount() int {
	return s.Count
}

// GetPokemon returns the value of Pokemon.
func (s *PokemonList) GetPokemon() []Pokemon {
	return s.Pokemon
}

// SetCount sets the value of Count.
func (s *PokemonList) SetCount(val int) {
	s.Count = val
}

// SetPokemon sets the value of Pokemon.
func (s *PokemonList) SetPokemon(val []Pokemon) {
	s.Pokemon = val
}

// Ref: #/components/schemas/TypeList
type TypeList struct {
	Types []TypeSummary `json:"types"`
}

// GetTypes returns the value of Types.
func (s *TypeList) GetTypes() []TypeSummary {
	return s.Types
}

// SetTypes sets the value of Types.
func (s *TypeList) SetTypes(val []TypeSummary) {
	s.Types = val
}

// Ref: #/components/schemas/TypeSummary
type TypeSummary struct {
	Name  string `json:"name"`
	Count int    `json:"count"`
}

// GetName returns the value of Name.
func (s *TypeSummary) GetName() string {
	return s.Name
}

// GetCount returns the value of Count.
func (s *TypeSummary) GetCount() int {
	return s.Count
}

// SetName sets the value of Name.
func (s *TypeSummary) SetName(val string) {
	s.Name = val
}

// SetCount sets the value of Count.
func (s *TypeSummary) SetCount(val int) {
	s.Count = val
}
