// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetHealthz implements getHealthz operation.
	//
	// Liveness and readiness probe.
	//
	// GET /healthz
	GetHealthz(ctx context.Context) (*Health, error)
	// GetPokemon implements getPokemon operation.
	//
	// One Pokemon by name.
	//
	// GET /pokemon/{name}
	GetPokemon(ctx context.Context, params GetPokemonParams) (GetPokemonRes, error)
	// GetRoot implements getRoot operation.
	//
	// Identify the service and the running build.
	//
	// GET /
	GetRoot(ctx context.Context) (*Identity, error)
	// ListPokemon implements listPokemon operation.
	//
	// List Pokemon, optionally filtered by type.
	//
	// GET /pokemon
	ListPokemon(ctx context.Context, params ListPokemonParams) (*PokemonList, error)
	// ListTypes implements listTypes operation.
	//
	// Every type present in the Pokedex, with a count.
	//
	// GET /types
	ListTypes(ctx context.Context) (*TypeList, error)
	// NewError creates *ErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
