// Code generated by ogen, DO NOT EDIT.
package api

type CreateBattleRes interface {
	createBattleRes()
}

type GetBattleRes interface {
	getBattleRes()
}

type GetMoveRes interface {
	getMoveRes()
}

type GetPokemonRes interface {
	getPokemonRes()
}

type GetReadyzRes interface {
	getReadyzRes()
}

type JoinBattleRes interface {
	joinBattleRes()
}

type ListPokemonMovesRes interface {
	listPokemonMovesRes()
}

type RegisterTrainerRes interface {
	registerTrainerRes()
}

type TakeTurnRes interface {
	takeTurnRes()
}
