// Code generated by ogen, DO NOT EDIT.
package api

type CreateBattleRes interface {
	createBattleRes()
}

type GetBattleRes interface {
	getBattleRes()
}

type GetPokemonRes interface {
	getPokemonRes()
}

type JoinBattleRes interface {
	joinBattleRes()
}

type RegisterTrainerRes interface {
	registerTrainerRes()
}

type TakeTurnRes interface {
	takeTurnRes()
}
